import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signOut, useSession } from "next-auth/react";
import { PlaylistContextProvider } from "../context/PlaylistContext";
import { SideBar } from "../components/SideBar";

const Home: NextPage = () => {
  const { data: session } = useSession();
  console.log("session", session);
  return (
    <div className={styles.container}>
      <PlaylistContextProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {session?.user && (
          <button onClick={() => signOut()}>
            {session?.user?.name} - Log out
          </button>
        )}
        <div className="d-flex">
          <div className="w-[20%]">
            <SideBar />
          </div>
        </div>
      </PlaylistContextProvider>
    </div>
  );
};

export default Home;
